# Generated by Django 6.0.3 on 2026-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0002_company_callback_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callback',
            options={'verbose_name': 'Обратный звонок', 'verbose_name_plural': 'Обратные звонки'},
        ),
        migrations.AddField(
            model_name='company',
            name='ai_prompt',
            field=models.TextField(blank=True, help_text='Здесь напиши роль бота и правила общения для этой компании.', null=True, verbose_name='Инструкция для ИИ(Промпт)'),
        ),
    ]
