# Generated by Django 6.0.3 on 2026-04-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0003_alter_callback_options_company_ai_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='ai_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ ИИ'),
        ),
    ]
